name: Select Template

on: push

env:
  API: 7178883361699344463187
  USER_ID: 63da7db6c2b671ace38e06b9
  PROJECT_ID: 648d16df33ca477727a362b5
  REPO_TEMPLATE: devmasyadi/SlotMachineUnity
  NEW_REPO_NAME: SDwkrHETKf1699344463176


jobs:
  build:

    runs-on: ubuntu-latest
    name: Select Template
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_BUILDER }}
          path: ./project
          token: ${{ secrets.TOKEN_BUILDER }}
      - name: Cache node modules
        if: always()
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ./project/node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('./project/package.json') }}
          restore-keys: ${{ runner.os }}-build-node-modules-
      - name: Install Dependencies
        if: ${{ always() && steps.cache-nodemodules.outputs.cache-hit != 'true' }}
        working-directory: "./project"
        run: npm i
      - name: Select
        working-directory: "./project"
        run: |
          node src/controllers/clone_template_action.js ${{ env.USER_ID }} ${{ env.PROJECT_ID }} ${{ secrets.TOKEN_BUILDER }} ${{ env.REPO_TEMPLATE }} ${{ env.NEW_REPO_NAME }}

   