name: Select Template

on: push

env:
  API: 5179667011698918241271
  USER_ID: 63cdee91f2d01e6ec1115636
  PROJECT_ID: 65436f5579c0322a68b969c3
  REPO_TEMPLATE: devmasyadi/SlotMachineUnity
  NEW_REPO_NAME: 8xQHglZLBo1698918241257


jobs:
  build:

    runs-on: ubuntu-latest
    name: Select Template
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_BUILDER }}
          path: ./project
          token: ${{ secrets.TOKEN_BUILDER }}
      - name: Cache node modules
        if: always()
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ./project/node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('./project/package.json') }}
          restore-keys: ${{ runner.os }}-build-node-modules-
      - name: Install Dependencies
        if: ${{ always() && steps.cache-nodemodules.outputs.cache-hit != 'true' }}
        working-directory: "./project"
        run: npm i
      - name: Select
        working-directory: "./project"
        run: |
          node src/controllers/clone_template_action.js ${{ env.USER_ID }} ${{ env.PROJECT_ID }} ${{ secrets.TOKEN_BUILDER }} ${{ env.REPO_TEMPLATE }} ${{ env.NEW_REPO_NAME }}

   