name: Select Template

on: push

env:
  API: 4535427801697879818072
  USER_ID: 63f5eaeb233cf2e0146c7cb5
  PROJECT_ID: 653396ff79c0322a683f3256
  REPO_TEMPLATE: devmasyadi/Hermifariz-HipHop
  NEW_REPO_NAME: gCEJAFJwYz1697879817385


jobs:
  build:

    runs-on: ubuntu-latest
    name: Select Template
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_BUILDER }}
          path: ./project
          token: ${{ secrets.TOKEN_BUILDER }}
      - name: Cache node modules
        if: always()
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ./project/node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('./project/package.json') }}
          restore-keys: ${{ runner.os }}-build-node-modules-
      - name: Install Dependencies
        if: ${{ always() && steps.cache-nodemodules.outputs.cache-hit != 'true' }}
        working-directory: "./project"
        run: npm i
      - name: Select
        working-directory: "./project"
        run: |
          node src/controllers/clone_template_action.js ${{ env.USER_ID }} ${{ env.PROJECT_ID }} ${{ secrets.TOKEN_BUILDER }} ${{ env.REPO_TEMPLATE }} ${{ env.NEW_REPO_NAME }}

   