name: Select Template

on: push

env:
  API: 6265069181696594358545
  USER_ID: 644fd356d59f93eb63726b00
  PROJECT_ID: 64977d859b9b460ebb3607d6
  REPO_TEMPLATE: devmasyadi/Kids-Coloring-Book-Unity
  NEW_REPO_NAME: TNoklzoomW1696594358088


jobs:
  build:

    runs-on: ubuntu-latest
    name: Select Template
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_BUILDER }}
          path: ./project
          token: ${{ secrets.TOKEN_BUILDER }}
      - name: Cache node modules
        if: always()
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ./project/node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('./project/package.json') }}
          restore-keys: ${{ runner.os }}-build-node-modules-
      - name: Install Dependencies
        if: ${{ always() && steps.cache-nodemodules.outputs.cache-hit != 'true' }}
        working-directory: "./project"
        run: npm i
      - name: Select
        working-directory: "./project"
        run: |
          node src/controllers/clone_template_action.js ${{ env.USER_ID }} ${{ env.PROJECT_ID }} ${{ secrets.TOKEN_BUILDER }} ${{ env.REPO_TEMPLATE }} ${{ env.NEW_REPO_NAME }}

   